steps:
- name: busybox
  args: ["mkdir", "./public"]
- name: 'gcr.io/$PROJECT_ID/hugo'
- name: busybox
  args: ["pwd"]
- name: busybox
  args: ["ls -lha"]
- name: 'gcr.io/$PROJECT_ID/wrangler'
  args: ["publish", "--env", "prod"]
- name: gcr.io/cloud-builders/curl
  entrypoint: bash
  args:
  - -c
  - >
    curl --request POST --header 'X-Auth-Email: ${_CF_EMAIL}' --header "X-Auth-Key: $$CF_API_KEY" --header 'Content-Type: application/json' --data '{"purge_everything":true}' https://api.cloudflare.com/client/v4/zones/${_CF_ZONE}/purge_cache
  secretEnv: ['CF_API_KEY']
secrets:
- kmsKeyName: projects/opshostweb-785737801/locations/global/keyRings/staticbuild/cryptoKeys/cloudflare
  secretEnv:
    CF_API_KEY: CiQA2p1DD87SQ1EEpTWqlyhg5IZM4/YouCCIRZgfQEGdDFTMRLwSTgDXnrextQY/d1bnS7FucX+vcyIhL6ka13/xTD/ln0/61u3TjshfIwDsyyfSWbvrQ/fBEb4zGanBpsP70L4A42C+tgCT0cIllUwtzeLuww==
substitutions:
  _CF_EMAIL: cloudflareemail
  _CF_ZONE: cloudflarezoneid
  _HOSTNAME: hostname
options:
  env:
  - LC_ALL=C.UTF-8
  - LANG=C.UTF-8
